import type { Metadata } from 'next';
import './globals.css';
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
} from '@/components/ui/navigation-menu';
import { marckScript, cormorantInfant, alegreya } from '@/components/ui/fonts';
import Header from '@/components/ui/header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ru'>
      <body
        className={`${cormorantInfant.variable} ${alegreya.variable} ${marckScript.variable} antialiased bg-background`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
