import type { Metadata } from 'next';
import './globals.css';
import { marckScript, cormorantInfant, alegreya } from '@/components/ui/fonts';
import Header from '@/components/shared/header';
import { cn } from '@/lib/utils';
import { LocationStoreProvider } from '@/providers/location-store-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ru'>
      <body
        className={cn(
          'antialiased bg-background',
          cormorantInfant.variable,
          alegreya.variable,
          marckScript.variable
        )}
      >
        <LocationStoreProvider>
          <main>
            <Header />
            {children}
          </main>
        </LocationStoreProvider>
      </body>
    </html>
  );
}
